config/routes.rb
Rails.application.routes.draw do
  root to: "results#new" 
  resources :results, only: [:create, :new, :show]
  devise_for :users
  resources :users, except: [:index]

  resources :composts do
    resources :pictures, only: [:create]
    resources :contributions, only: [:create, :update, :new]
    resources :timeslots, only: [:create, :destroy]
  end
  resources :conversations, only: [:create] do
    resources :messages, only: [:create, :index]
  end
end

app/models/compost.rb
class Compost < ApplicationRecord
validates :title,
  presence: { message: "ne peut pas être vide"},
  length: { in: 3..50, message: "a une longueur inappropriée" }
validates :address,
  presence: { message: "ne peut pas être vide"},
  length: { in: 3..50, message: "a une longueur inappropriée" }
validates :zipcode, 
  presence: { message: "ne peut pas être vide"},
  inclusion: { in: ["75001", "75002", "75003", "75004", "75005", "75006", "75007", "75008", "75009", "75010", "75011", "75012", "75013", "75014", "75015", "75016", "75017", "75018", "75019", "75020"], message: "est invalide, il doit correspondre à un arrondissement parisien" }
validates :description,
  presence: { message: "ne peut pas être vide"},
  length: { maximum: 160, message: "a une longueur inappropriée" }

  acts_as_taggable_on :districts, :compositions

  # N - 1 association with composters (users)
  belongs_to :composter, class_name: 'User'

  # 1 - N association with timeslots
  has_many :timeslots, dependent: :destroy

  # 1 - N association with contributions, as supplied_compost
  has_many :contributions, foreign_key: 'supplied_compost_id'
  # N - N association with contributors (users), via contributions
  has_many :contributors, through: :contributions, source: :contributor

  # 1 - N association with result_lines
  has_many :result_lines
  # N - N association with results, via result_lines
  has_many :results, through: :result_lines

  # Active Storage picture association
  has_one_attached :picture

  # use user input to create/update district tag
  before_save :tag_with_district
  before_save :update_is_open

  #geocoder 
  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    return self.address + " " + self.zipcode + " " + self.city + ", " + self.country
  end 

  private

  def tag_with_district
    self.district_list = self.zipcode
  end

  def update_is_open
    if self.filling && self.filling >= 100
      self.is_open = false
    end
  end

  
end

app/controllers/composts_controller.rb
class CompostsController < ApplicationController
  include UsersHelper
  
  before_action :authenticate_user, except: [:show, :index]
  before_action :set_compost, except: [:new, :create, :index]
  before_action :has_access?, except: [:new, :create, :show, :index]
  before_action :profile_enhancement, only: [:index]

  # GET /composts
  def index
    @composts = Compost.all
  end

  # GET /composts/1
  def show
    @contributions = @compost.contributions
    @slots = @compost.timeslots.order(:weekday, :start_time)
  end

  # GET /composts/new
  def new
    @compost = Compost.new
  end

  # GET /composts/1/edit
  def edit
  end

  # POST /composts
  def create
    @compost = current_user.owned_composts.new(compost_params)
    @compost.city = "Paris"
    @compost.country = "France"
    
    if @compost.save
      redirect_to @compost, notice: 'Le compost a bien été créé.' 
    else
      render :new
    end
  end

  # PATCH/PUT /composts/1
  def update
    respond_to do |format|
      if @compost.update(compost_params)
        @compost.composition_list = compost_params[:composition_list]
        @compost.picture.attach(params[:picture]) if params[:picture]
        @compost.save()
        format.html { redirect_to @compost, notice: 'Le compost a été mis à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /composts/1
  def destroy
    @compost.destroy
    respond_to do |format|
      format.html { redirect_to composts_url, notice: 'Le compost a été détruit.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compost
      @compost = Compost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compost_params
      params.require(:compost).permit(
        :title, :address, :zipcode, :city,
        :country, :description, :access_data,
        :image_url, :is_open, :filling,
        :picture,
        :composition_list => []
      )
    end

    # Method to ask the user to add more data to his profile on the welcome page ==> to move when we have the final welcome page
    def profile_enhancement
      if profile_completed?(50) == false
          flash.now[:notice] = "Votre profil n'est rempli qu'à #{current_user.profile_completion}%. A l'occasion, passez le compléter #{view_context.link_to('par ici', edit_user_path(current_user))}"      
      end
    end

  def authenticate_user
    unless current_user
      flash[:error] = "Merci de te connecter afin de voir cette page."
      redirect_back(fallback_location: root_path)
    end
  end

  def has_access?
    unless current_user && is_owner?(@compost)
      flash[:error] = "Cette action est réservée au propriétaire de ce compost."
      redirect_back(fallback_location: compost_path(@compost))
    end
  end
end

app/helpers/composts_helper.rb
module CompostsHelper
end

app/views/composts/_contribute.html.erb
<h1>Contribuer à ce compost</h1>
<%= form_tag compost_contributions_path(@compost), method:"post" do %>

  <div class="field center">
    <%= text_area_tag :message, nil, placeholder: "Écris un gentil message pour le gestionnaire de ce compost (obligatoire)", class:"form-control" %>
  </div>
  <% if current_user%>
    <%= hidden_field_tag(:contributor_id, current_user.id) %>
  <% end %>
  <%= hidden_field_tag(:supplied_compost_id, @compost.id) %>
  <br>

  <div class="actions center">
    <%= submit_tag "Demander à contribuer", class:"btn btn-primary" %>
  </div>
  
<% end %>

app/views/composts/_form.html.erb
<%= form_with(model: compost, local: true) do |form| %>
<% if compost.errors.any? %>
<div id="error_explanation">
  <h2>Petit problème :</h2>
  <ul>
    <% compost.errors.full_messages.each do |message| %>
      <% if message.split.slice(0) == "Title" %>
        <li>Le titre <%= message.split.slice(1..-1).join(" ") %></li>
      <% elsif message.split.slice(0) == "Description" %>
        <li>La description <%= message.split.slice(1..-1).join(" ") %></li>
      <% elsif message.split.slice(0) == "Address" %>
        <li>L'adresse <%= message.split.slice(1..-1).join(" ") %></li>
      <% else %>
        <li>Le code postal <%= message.split.slice(1..-1).join(" ") %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<% end %>

<section id="cover">
  <div id="cover-caption">
    <div id="container" class="container">
      <div class="row text-white ">
        <div class="col-sm-6 offset-sm-3 text-center">
          <br>
          <br><br>
          <div class="info-form">
            <div class="form-group">
              <div class="input-group-prepend faw">
                <%= form.text_field :title, class:"form-control", placeholder:raw("&#xf035;  Titre (obligatoire, 3 - 30 caractères)")  %>
              </div> <br>
              <div class="input-group-prepend faw">
                <%= form.text_area :description, class:"form-control", placeholder:raw("&#xf039;  Description (obligatoire, max 160 caractères)") %>
              </div><br>
              <div class="input-group-prepend faw">
                <%= form.text_field :address, class:"form-control", placeholder:raw("&#xf041;  Adresse (obligatoire, 3-50 caractères)")  %>
              </div><br>
              <div class="input-group-prepend faw">
                <%= form.text_field :zipcode, class:"form-control", placeholder:raw("&#xf041;  Code postal parisien (obligatoire)") %>
              </div><br>


              <div class="input-group-prepend faw my-2">
                <%= form.label :agrumes, class:'text-dark mr-2' %>
                <%= form.check_box(:composition_list, {:multiple => true}, "agrumes", nil) %>

                <%= form.label :bananes, class:'text-dark mx-2' %>
                <%= form.check_box(:composition_list, {:multiple => true}, "bananes", nil) %>
              </div>

              <div class="input-group-prepend faw my-2">
                <%= form.label :bio, class:'text-dark mr-2' %>
                <%= form.check_box(:composition_list, {:multiple => true}, "bio", nil) %>

                <%= form.label :coquilles, class:'text-dark mx-2' %>
                <%= form.check_box(:composition_list, {:multiple => true}, "coquilles", nil) %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group-prepend faw my-2">
                <h6 class="text-dark mr-2">Choisir une photo :</h6>
                <%= form.file_field :picture %>
              </div>

              <div class="input-group-prepend faw my-2">
                <%= form.label :"Ouvrir le compost aux contributions", class: "text-dark mr-2 h6" %>
                <%= form.check_box :is_open %>
              </div>

              <div class="input-group-prepend faw my-2">
                <%= form.label :Remplissage, class: "text-dark mr-2 h6" %>
                <%= form.number_field :filling, class:"number-field" %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="actions center">
        <%= form.submit 'Valider les informations', class:"btn btn-primary"%>
      </div>
    </div>
  </div>

  <% end %>

app/views/composts/_jumbotron.html.erb
  <div class="small-jumbotron">
    <div class="container h-100">
      <div class="row jumbotron-row">
        <div class="col-lg-8 col-sm-12">
            <h1 class="display-3 mx-5 text-center small-jumbotron-title"><i class="fas fa-carrot mr-2"></i>Liste de tous les composts</h1> 
        </div>
      </div>
    </div>
  </div>

app/views/composts/edit.html.erb
<br><h1 class="center">Editer mon compost</h1>

<%= render 'form', compost: @compost %>

<div class="center">
<%= link_to 'Revenir à la page accueil', composts_path, class:"btn btn-link"%>
</div>

app/views/composts/index.html.erb
<% content_for :title, "OkCompost / Compost" %>
<%= render "jumbotron" %>
<div class="container-fluid mt-5 mx-5">
  <div class="row mx-5 mb-5">
    <% @composts.each do |compost| %>
     <div class="card-deck">
      <div class="d-flex align-items-stretch">
        <div class="card search-card border-success mb-3 mx-5">
          <div class="card-header bg-success text-white font-weight-bolder"><%= compost.title%></div>
          <div class="card-body">
            <% if compost.picture.attached? %>
              <%= image_tag compost.picture, class: "img-tag" %>
            <% else %>
              <%= image_tag 'http://odil.tv/wp-content/uploads/2019/06/b00bc6e_2018122245.0.2235366676compost_web-1280x640.jpg', style:"height: auto; max-width:100%" %>
            <% end %>
            <h4 class="card-title"><%=link_to compost.composter.username, user_path(compost.composter) %></h4>
            <div class="row">
              <%= link_to compost.district_list.to_s, {
                :controller => "results", :action => "create",
                :result => {
                  :district => compost.district_list.to_s, :composition => []
                }
              },
              :method => "post", :class => 'btn btn-info mx-1 mb-1'
              %>
            </div>
            <div class="row">
              <% compost.composition_list.sort.each do |composition_tag| %>
                <%= link_to composition_tag.to_s, {
                  :controller => "results", :action => "create",
                  :result => {
                    :district => nil, :composition => [composition_tag.to_s]
                  }
                },
                { :method => "post", :class => 'btn btn-outline-info mx-1 mb-1'} %>
              <% end %>
            </div>
            <p class="card-text"><%= compost.description %></p>
            <%= link_to "Voir ce compost", compost_path(compost), class: "btn btn-warning" %>
          </div>
        </div>
      </div>
     </div>
    <% end %>
  </div>
</div>

app/views/composts/new.html.erb
<% content_for :title, "OkCompost / Créer un compost" %>
<br><h1 class="center">Créer mon nouveau compost</h1>

<%= render 'form', compost: @compost %>

<div class="center">
<%= link_to 'Revenir à la page accueil', composts_path, class:"btn btn-link" %>
</div>

app/views/composts/show.html.erb
<% content_for :title, "OkCompost / Compost" %>
<div class="container">
  <br>
  <h1 class="center">Compost <%= @compost.title %></h1>
</div>
<br>
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to 'Infos', '#infos', { 'data-toggle' => "tab", :class => "nav-link active" } %>
    </li>
    <% unless is_owner?(@compost) %>
      <li class="nav-item">
        <%= link_to 'Disponibilités', '#timeslotsList', { 'data-toggle' => "tab", :class => "nav-link" } %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Historique des contributions', '#contributions', { 'data-toggle' => "tab", :class => "nav-link" } %>
      </li>
      <% if is_owner?(@compost) %>
        <li class="nav-item">
          <%= link_to 'Gérer mes disponibilités', '#timeslotsManagement', { 'data-toggle' => "tab", :class => "nav-link" } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contributions en attente', '#waiting-contributions', { 'data-toggle' => "tab", :class => "nav-link" } %>
        </li>
      <%end%>
    <% end %>
  </ul>
  <div id="myTabContent" class="tab-content py-4">
    <div class="tab-pane fade active show" id="infos">
      <table class='table table-borderless'>
        <tbody>
          <div class="container mt-4">
            <div class="card shadow-lg">
              <div class="row banniere">
                <div class="col-8">
                  <% if @compost.picture.attached? %>
                    <%= image_tag @compost.picture, style:"height: auto; max-width:100%" %>
                  <% else %>
                    <%= image_tag 'http://odil.tv/wp-content/uploads/2019/06/b00bc6e_2018122245.0.2235366676compost_web-1280x640.jpg', style:"height: auto; max-width:100%" %>
                  <% end %>
                </div>
                <div class="col-4 d-flex row flex-column">
                  <div class="container mt-4">
                    <h3 class="h3-up" ><%= @compost.title %> </h3>
                    <br>
                    <h4> Gestionnaire :</h4>
                    <p><%= link_to @compost.composter.username, user_path(@compost.composter.id), class: "btn btn-link"%></p>
                    <h4>Description :</h4>
                    <p><%= @compost.description %></p>
                    <br>
                    <h4>Tags :</h4>
                    <p>
                      <%= link_to @compost.district_list.to_s, {
                        :controller => "results", :action => "create",
                        :result => {
                          :district => @compost.district_list.to_s, :composition => []
                          }
                        },
                        :method => "post", :class => 'btn btn-outline-warning rounded-pill'
                      %><br>
                      <br>
                      <% @compost.composition_list.sort.each do |composition_tag| %>
                        <%= link_to composition_tag.to_s, {
                            :controller => "results", :action => "create",
                            :result => {
                              :district => nil, :composition => [composition_tag.to_s]
                              }
                            },
                            { :method => "post", :class => 'btn btn-outline-info rounded-pill'}
                  %>
                      <% end %><br>
                      <br>
                    </p>
                    <h4>Niveau de remplissage actuel :</h4>
                    <div >
                      <% if @compost.filling < 75 %>
                        <span class="badge badge-pill badge-light text-success px-3 pt-2">
                          <h5><%= @compost.filling %>%</h5>
                        </span>
                        <div class="progress progress-bar-vertical text-center">
                          <div class="progress-bar text-dark bg-success" role="progressbar" aria-valuenow=<%= @compost.filling %> aria-valuemin="0" aria-valuemax="100" style="height: <%= @compost.filling %>%;">
                          </div>
                        </div>
                      <% elsif @compost.filling < 95 %>
                        <span class="badge badge-pill badge-light text-warning px-3 pt-2">
                          <h5><%= @compost.filling %>%</h5>
                        </span>
                        <div class="progress progress-bar-vertical text-center">
                          <div class="progress-bar text-dark bg-warning" role="progressbar" aria-valuenow=<%= @compost.filling %> aria-valuemin="0" aria-valuemax="100" style="height: <%= @compost.filling %>%;">
                          </div>
                        </div>
                      <% else %>
                        <span class="badge badge-pill badge-light text-danger px-3 pt-2">
                          <h5><%= @compost.filling %>%</h5>
                        </span>
                        <div class="progress progress-bar-vertical text-center">
                          <div class="progress-bar text-dark bg-danger" role="progressbar" aria-valuenow=<%= @compost.filling %> aria-valuemin="0" aria-valuemax="100" style="height: <%= @compost.filling %>%;">
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                  <br>
                  <br>
                  <div class="modal-footer mt-auto p-2 bd-highligh justify-content-between">
                    <% if @compost.is_open %>
                      <span class="badge badge-pill badge-light text-success px-3 pt-2">
                        <h5><i class="fas fa-check"></i> Ouvert aux contributions</h5>
                      </span>
                    <% else %>
                      <span class="badge badge-pill badge-danger px-3 pt-2">
                        <h5>Fermé</h5>
                      </span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <br>
          </div>
          <!-- Access -->
          <tr>
            <h3>Accès</h3>
            <% if display_access_data?(@compost) || is_owner?(@compost) %>
              <th width=33%>
                <h4 class='text-secondary'>Adresse</h4>
              </th>
              <td width=33%>
                <p><%= @compost.address %></p>
              </td>
              <td width=33% rowspan=6> <%= render 'application/map'%></td>
            </tr>
            <tr>
              <th>
                <h4 class='text-secondary'>Code postal</h4>
              </th>
              <td>
                <p><%= @compost.zipcode %></p>
              </td>
            </tr>
            <tr>
              <th>
                <h4 class='text-secondary'>Ville</h4>
              </th>
              <td>
                <p><%= @compost.city %></p>
              </td>
            </tr>
            <tr>
              <th>
                <h4 class='text-secondary'>Pays</h4>
              </th>
              <td>
                <p><%= @compost.country %></p>
              </td>
            </tr>
            <tr>
              <th>
                <h4 class='text-secondary'>Plan d'accès</h4>
              </th>
              <td>
                <p><%= @compost.access_data %>
                </p>
              </tr>
            </tbody>
          <%else%>
            <h4 class="center">Contribuer au compost pour voir les infos d'accès.</h4>
            <br>
            <br>
          <%end%>
        </table>
        <br>
        <div class="center">
          <% if is_owner?(@compost) %>
            <%= link_to 'Editer le compost', edit_compost_path(@compost), class: "btn btn-primary" %>
            <%= link_to 'Supprimer le compost', @compost,  method: :delete, data: { confirm: 'Etes vous sure de vouloir supprimer le compost ?' }, class: "btn btn-danger" %><br>
          <% end %>
        </div>
        <br>
        <br>
        <% if display_contribute_form?(@compost) %>
          <%= render 'composts/contribute' %>
        <% end %>
        <div class="center">
          <%= link_to 'Retourner à la page accueil', root_path, class: "btn btn-link" %>
        </div>
      </div>
      
      <div class="tab-pane fade" id="timeslotsList">
        <%= render 'timeslots/slots_list' %>
      </div>

      <div class="tab-pane fade" id="contributions">
        <table class="table table-hover table">
          <thead class='thead-light'>
            <tr>
              <th>
                <h4 class='text-secondary'>Contributions au compost</h4>
              </th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <thead>
              <th>
                <h3 class='text-secondary'>Utilisateur·ice</h3>
              </th>
              <th>
                <h3 class='text-secondary'>Profil</h3>
              </th>
            </thead>
            <% @compost.contributions.each do |contribution| %>
              <tr>
                <th>
                  <h4 class='text-secondary'><%= contribution.contributor.username %></h4>
                </th>
                <td>
                  <p><%=  link_to "Voir le profil", user_path(contribution.contributor), class:"btn btn-primary" %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane fade" id="timeslotsManagement">
        <%= render 'timeslots/new' %>
        <%= render 'timeslots/slots_management' %>
      </div>
      <div class="tab-pane fade" id="waiting-contributions">
        <table class="table table-hover table">
          <tbody>
            <tr>
              <h3 class='text-secondary'></h3>
              <br>
              <%= render 'contributions/contributions_list' %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>