config/routes.rb
Rails.application.routes.draw do
  root to: "results#new" 
  resources :results, only: [:create, :new, :show]
  devise_for :users
  resources :users, except: [:index]

  resources :composts do
    resources :pictures, only: [:create]
    resources :contributions, only: [:create, :update, :new]
    resources :timeslots, only: [:create, :destroy]
  end
  resources :conversations, only: [:create] do
    resources :messages, only: [:create, :index]
  end
end

app/models/result.rb
class Result < ApplicationRecord
  enum search_mode: [:normal, :strict, :cool]

  # N -1 association with users
  belongs_to :user, optional: true

  # 1 - N association with result_lines
  has_many :result_lines
  # N - N association with composts, via result_lines
  has_many :composts, through: :result_lines

  before_create :search
  after_create :save_lines

  def search_by_district
    composts = Compost.tagged_with(self.district)
    composts.each do |compost|
      self.result_lines.new(compost_id: compost.id)
    end
  end

  def search_by_composition
    case self.search_mode
    when 'strict'
      composts = Compost.tagged_with(self.composition, :on => :compositions, :match_all => true)
    when 'cool'
      composts = Compost.tagged_with(self.composition, :on => :compositions, :any => true)
    else
      composts = Compost.tagged_with(self.composition)
    end

    composts.each do |compost|
      self.result_lines.new(compost_id: compost.id) if compost.is_open
    end
  end

  def search_by_both
    district_composts = Compost.tagged_with(self.district)
    case self.search_mode
    when 'strict'
      composts = district_composts.tagged_with(self.composition, :on => :compositions, :match_all => true)
    when 'cool'
      composts = district_composts.tagged_with(self.composition, :on => :compositions, :any => true)
    else
      composts = district_composts.tagged_with(self.composition)
    end
    composts.each do |compost|
      self.result_lines.new(compost_id: compost.id)
    end
  end

  private

  def search
    if !self.district.empty? && self.composition.empty?
      self.search_by_district
    elsif self.district.empty? && self.composition.any?
      self.search_by_composition
    elsif !self.district.empty? && self.composition.any?
      self.search_by_both
    end
  end

  def save_lines
    self.result_lines.each do |result_line|
      result_line.save!()
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show]
  before_action :search_must_have_params, only: [:create]

  # GET /results/1
  def show
    @input_array = []
    @result.composts.each do |compost|
      # send input to the JS MapIni function with for each result line an array with : latitude, longitude and compost_id
      @input_array << [compost.latitude, compost.longitude, compost.id]
    end 
  puts "***********************"
  print @coordinates_array
  end

  # GET /results/new
  def new
    @result = Result.new
    @compositions = Compost.tag_counts_on("compositions")

    if current_user
      if current_user.owned_composts.size > 0 && current_user.supplied_composts.size == 0
        @composts = current_user.owned_composts.sample([3, current_user.owned_composts.size].min)
      elsif current_user.supplied_composts.size > 0
        @composts = current_user.supplied_composts.sample([3, current_user.supplied_composts.size].min)
      else
        @composts = Compost.all.sample(3)
      end
    else
      @composts = Compost.all.sample(3)
    end

    if @composts.size < 3
      (3 - @composts.size).times do
        @composts << Compost.all.sample
      end
    end
  end

  # POST /results
  def create
    @result = Result.new(result_params)
    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Voici les résultats de votre recherche :' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # forbid empty search
    def search_must_have_params
      if result_params[:district].empty? && result_params[:composition] == nil
        flash[:error] = "Merci de sélectionner au moins un critère de recherche.\n
        Pour voir tous les composts, rendez-vous sur la page #{view_context.link_to('tous les composts', composts_path)}"
        redirect_back(fallback_location: root_path)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(
        :district , :search_mode,
        :composition => []
      )
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_about.html.erb
<div class="container text-center">
  <h3 class="my-5 text-secondary">A Propos De OK COMPOST</h3>
  <hr class="long mb-5">
</div>

<div class="container tm">
  <div id="text1" class="mb-3">
    <hr class="long mb-4">
    <p class="text-secondary text-center mb-4"><strong>Des petits gestes quotidiens permettent de réduire les déchets et certaines pratiques permettent même de les réutiliser au quotidien. C'est le cas du compost qui permet la création d'engrais naturel. <br>
    OK COMPOST est là pour rendre tout ça plus clair, facile et accessible à tous. </strong>
    </p>
    <hr class="long">
  </div>
  <div>
    <p class="text-center text-secondary mb-3">OK COMPOST permet de rapprocher les différents acteurs qui peuvent intervenir tout au long du processus de compostage et s'adresse donc à plusieurs types de personnes :
    </p>
    <p class="text-center text-secondary"> Vous êtes un <strong>citoyen consommateur</strong> voulant recycler vos déchets alimentaires mais ne possédant pas de compost : OK COMPOST vous aide à trouver des composts près de chez vous. <br>
    <%= link_to 'FAIS UNE RECHERCHE', root_path,class:"text-center" %></p>
    <p class="text-center text-secondary"> Vous êtes un <strong>citoyen propriétaire</strong> d'un compost et vous voulez en faire profiter votre voisinage. <br>   <%= link_to 'CREES UN COMPOST', new_compost_path,class:"text-center" %></p>
    <p class="text-center text-secondary"> Vous êtes un <strong>agriculteur</strong> ou un <strong>citadin</strong> possédant un jardin/potager et vous voudriez pouvoir utiliser l'engrais créé. <br> <%= link_to 'VOIR LES COMPOSTS REMPLIS', root_path,class:"text-center" %> </p>
  </div>
</div>

<hr class="my-3"> 

<div class="container">
  <div class="card-deck">
    <div class="card border-0 text-center card-about">
      <%= image_tag "aboutus_pictures/epluchures.png", class: "about-picture mx-auto" %>
      <div class="card-body">
        <p class="card-text">Redonnez le sourire à vos épluchures. Au lieu de jeter vos déchets alimentaires dans le bac à ordures, gardez-les pour en faire du compost...</p>
      </div>
    </div>
    <div class="card border-0 text-center card-about">
      <%= image_tag "aboutus_pictures/composteur.png", class: "about-picture mx-auto" %>
      <div class="card-body">
        <p class="card-text">...en quelques mois les déchets seront transformés en compost...</p>
      </div>
    </div>
    <div class="card border-0 text-center card-about">
      <%= image_tag "aboutus_pictures/potager.png", class: "about-picture mx-auto" %>
      <div class="card-body">
        <p class="card-text">...et deviendront un engrais 100% naturel qui permettra de nourrir les sols de jardins, potagers et même ceux de champs agricoles !</p>
      </div>
    </div>
  </div>
</div>

<p class="text-secondary text-center mb-5">Pour toute autre question, n'hésitez pas à regarder <%= link_to 'la FAQ', page_path('faq') %> </p>

<hr class="long mb-5">

app/views/results/_form.html.erb
<%= form_with(model: result, local: true, html: { class: 'info-form'}) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="jumbotron">
    <div class="container h-100">
      <div class="row" id="jumbotron-row">
        <div class="col-lg-6 col-sm-12">
            <h1 id="jumbotron-title" class="display-3 mx-5 text-center">Offrez de belles rencontres à vos épluchures !</h1> 
        </div>
        <div class="col-lg-6 col-sm-12">
          <div class="card mx-5">
            <div class="card-body">
              <h3 class="card-title">Cherchez un compost !</h3>
              <h6 class="card-subtitle mb-2 text-muted mt-3"> Renseignez vos critères de sélection :</h6>
              
              <div>
                <%= select_tag("result[district]", options_for_select([['Arrondissement de Paris', ""],['1er', '75001'], ['2ème', '75002'], ['3ème', '75003'], ['4ème', '75004'], ['5ème', '75005'], ['6ème', '75006'], ['7ème', '75007'], ['8ème', '75008'], ['9ème', '75009'], ['10ème', '75010'], ['11ème', '75011'], ['12ème', '75012'], ['13ème', '75013'], ['14ème', '75014'], ['15ème', '75015'], ['16ème', '75016'], ['17ème', '75017'], ['18ème', '75018'], ['19ème', '75019'], ['20ème', '75020']]), class: "form-control-welcome mb-2") %>
              </div>

              <div>
                <%= select_tag("result[search_mode]", options_for_select([['Recherche normale', 'normal'], ['Recherche stricte (uniquement les critères)', 'strict'], ['Recherche cool (au moins un critère)', 'cool']]), class: "form-control-welcome mb-2") %>
              </div>
              
              <div class="row mt-2 mb-3">
                <% @compositions.each do |composition_tag| %>
                  <div class="field mr-2">
                    <%= form.label composition_tag.name.to_sym, class: "ml-3 mr-2" %>
                    <%= form.check_box(:composition, {:multiple => true}, composition_tag.name, nil) %>
                  </div>
                <% end %>
              </div>

              <button class="btn btn-primary px-5 mr-3">Et zou !</button>
              <p class="my-3">Ou alors : </p>
              <%= link_to "Créer un compost !", new_compost_path, class: "btn btn-info" %>
            </div>
          </div>  
        </div>
      </div>
    </div>

  </div>

<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<% content_for :title, "OkCompost / Notice" %>
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<% content_for :title, "Bienvenue sur Ok Compost" %>
<%= render 'form', result: @result %>
<%= render 'about' %>
<div class="container-fluid">
  <h2 class="mb-5 text-secondary text-center"><i class="fas fa-carrot"></i> Voici des exemples de super composts :</h2>
  <div class="row mx-5 mb-5">
    <% @composts.each do |compost| %>
     <div class="card-deck">
      <div class="d-flex align-items-stretch">
        <div class="card search-card border-success mb-3 mx-5">
          <div class="card-header bg-success text-white font-weight-bolder"><%= compost.title%></div>
          <div class="card-body">
            <% if compost.picture.attached? %>
              <%= image_tag compost.picture, class: "img-tag" %>
            <% else %>
              <%= image_tag 'http://odil.tv/wp-content/uploads/2019/06/b00bc6e_2018122245.0.2235366676compost_web-1280x640.jpg', style:"height: auto; max-width:100%" %>
            <% end %>
            <h4 class="card-title"><%=link_to compost.composter.username, user_path(compost.composter) %></h4>
            <div class="row">
              <%= link_to compost.district_list.to_s, {
                :controller => "results", :action => "create",
                :result => {
                  :district => compost.district_list.to_s, :composition => []
                }
              },
              :method => "post", :class => 'btn btn-info mx-1 mb-1'
              %>
            </div>
            <div class="row">
              <% compost.composition_list.sort.each do |composition_tag| %>
                <%= link_to composition_tag.to_s, {
                  :controller => "results", :action => "create",
                  :result => {
                    :district => nil, :composition => [composition_tag.to_s]
                  }
                },
                { :method => "post", :class => 'btn btn-outline-info mx-1 mb-1'} %>
              <% end %>
            </div>
            <p class="card-text"><%= compost.description %></p>
            <%= link_to "Voir ce compost", compost_path(compost), class: "btn btn-warning" %>
          </div>
        </div>
      </div>
     </div>
    <% end %>
  </div>
</div>

app/views/results/show.html.erb
<head>
  <% provide :head_tags do %>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
      let input_array = <%= @input_array %>;
      let result = <%= @result.id %>
      console.log(input_array.length);
      if ( input_array.length > 0 ){
        initMap( input_array, result );
        }
    });
    </script>
  <% end %>
</head>

<% content_for :title, "OkCompost / Résultats" %>
<div class="container-fluid">
  <h1 class="my-2">Résultats :</h1>
  <div id="result-page" class="row">
    <div class="col-6 h-100">
      <div id='search-results'class="row">
        <% if @result.result_lines.length == 0 %>
          <h2 class="ml-5">Il n'y a aucun résultat pour cette recherche...</h2>
        <% end %>
        <% @result.result_lines.each do |result_line| %>
          <%= render result_line %>
        <% end %>
      </div>
    </div>
    <div id='result-map' class="col-6"></div>
  </div>
  <%= link_to 'Nouvelle recherche', root_path, class: 'btn btn-lg btn-info mb-3' %>
</div>

app/views/results/show.js.erb
console.log()
let locations = [
    ['<%= @result.result_lines[0].compost.full_street_address %>', '<%= @result.result_lines[0].compost.latitude %>','<%= @result.result_lines[0].compost.longitude %>'],
    ['<%= @result.result_lines[1].compost.full_street_address %>', '<%= @result.result_lines[1].compost.latitude %>','<%= @result.result_lines[1].compost.longitude %>']
  ];

let map = new google.maps.Map(document.getElementById('map'), {
  zoom: 7,
  center: new google.maps.LatLng('<%= request.location.latitude %>', '<%= request.location.longitude %>'),
  mapTypeId: google.maps.MapTypeId.ROADMAP
});

let infowindow = new google.maps.InfoWindow();

let marker, i;

for (i = 0; i < locations.length; i++) {  
  marker = new google.maps.Marker({
    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
    map: map
  });

  google.maps.event.addListener(marker, 'click', (function(marker, i) {
    return function() {
      infowindow.setContent(locations[i][0]);
      infowindow.open(map, marker);
    }
  })(marker, i));
}