config/routes.rb
Rails.application.routes.draw do
  root to: "results#new" 
  resources :results, only: [:create, :new, :show]
  devise_for :users
  resources :users, except: [:index]

  resources :composts do
    resources :pictures, only: [:create]
    resources :contributions, only: [:create, :update, :new]
    resources :timeslots, only: [:create, :destroy]
  end
  resources :conversations, only: [:create] do
    resources :messages, only: [:create, :index]
  end
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  # N- 1 association with compost
  belongs_to :compost

  validates :weekday, presence: true,
  numericality: { only_integer: true },
  inclusion: { in: 1..7 }

  validates :start_time, presence: true,
  length: { is: 4 },
  format: { with: //, message: "l'heure de début doit être au format HH:MM" }

  validates :end_time, presence: true,
  length: { is: 4 },
  format: { with: //, message: "l'heure de fin doit être au format HH:MM" }

  validate :end_later_than_starts

  before_validation :convert_times

  def nice_day
    case self.weekday
    when 1
      "Lundi"
    when 2
      "Mardi"
    when 3
      "Mercredi"
    when 4
      "Jeudi"
    when 5
      "Vendredi"
    when 6
      "Samedi"
    when 7
      "Dimanche"
    end
  end

  def nice_slot
    "#{nice_start_time} à #{nice_end_time}"
  end

  private

  def convert_times
    self.start_time.delete!(':') if self.start_time
    self.end_time.delete!(':') if self.end_time
  end

  def end_later_than_starts
    errors.add(:end_time, "doit se terminer après l'heure de début") if (start_time && end_time && end_time <= start_time)
  end

  def nice_time(time)
    time.slice(0..1) + 'h' + time.slice(2..3)
  end

  def nice_start_time
    nice_time(self.start_time)
  end

  def nice_end_time
    nice_time(self.end_time)
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  include UsersHelper

  before_action :authenticate_user
  before_action :set_compost
  before_action :has_access?
  before_action :set_timeslot, only: [:destroy]

  def create
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.compost_id = @compost.id
    if @timeslot.save
      redirect_to @compost, notice: 'Le créneau a bien été ajouté.'
    else
      flash[:error] = "Ce créneau n'a pas pu être validé."
      redirect_to @compost
    end
  end

  def destroy
    @timeslot.destroy
    redirect_to compost_path(@compost), notice: 'Le créneau a bien été supprimé.'
  end

  private

  def timeslot_params
    params.require(:timeslot).permit(
      :weekday, :start_time, :end_time
    )
  end

  def set_timeslot
    @timeslot = Timeslot.find(params[:id])
    puts @timeslot.id
  end

  def set_compost
    @compost = Compost.find(params[:compost_id])
  end

  def authenticate_user
    unless current_user
      flash[:error] = "Cette action est réservée à un·e untilisat·eur·rice connecté·e."
      redirect_back(fallback_location: root_path)
    end
  end

  def has_access?
    unless current_user && is_owner?(@compost)
      flash[:error] = "Cette action est réservée au propriétaire de ce compost."
      redirect_back(fallback_location: compost_path(@compost))
    end
  end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/_new.html.erb
<h4>Ajouter un créneau :</h4>
<%= form_tag compost_timeslots_path(@compost), method:"post" do %>

  <div class="field">
    <%= label_tag :weekday, "Jour : " %>
    <%= select_tag('timeslot[weekday]', options_for_select([
      ["Lundi", 1], ["Mardi", 2], ["Mercredi", 3],["Jeudi", 4],["Vendredi", 5], ["Samedi", 6], ["Dimanche", 7]
      ]))
    %>
  </div>

  <div class="field">
    <%= label_tag :start_time, "Heure de début :" %>
    <%= text_field_tag('timeslot[start_time]', nil, placeholder: 'ex. 07:30')
    %>
  </div>

  <div class="field">
    <%= label_tag :end_time, "Heure de fin : (doit être postérieure à l'heure de début)" %>
    <%= text_field_tag('timeslot[end_time]', nil, placeholder: 'ex. 07:45')
    %>
  </div>

  <%= hidden_field_tag('timeslot[compost_id]', @compost.id) %>

  <div class="actions">
    <%= submit_tag "Ajouter le créneau", class:"btn btn-sm btn-outline-success" %>
  </div>
<% end %>

app/views/timeslots/_slots_list.html.erb
<table class="table table-hover table-border">
  <thead>
    <th>Jour</th>
    <th class='text-center' colspan="100%">Créneaux</th>
  </thead>
  <% ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"].each_with_index do |day, index| %>
    <tr>
      <th><%= day %></th>
      <% @compost.timeslots.each do |timeslot| %>
        <% if timeslot.weekday == index + 1 %>
          <td>
            <%= timeslot.nice_slot %>
          </td>
        <% end %>
      <% end %>
      <td colspan='100%'></td>
    </tr>
  <% end %>
</table>

app/views/timeslots/_slots_management.html.erb
<table class="table table-hover my-2">
  <thead>
    <th>Jour</th>
    <th>Créneau</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <th><%= slot.nice_day %></th>
        <td><%= slot.nice_slot %></td>
        <td>
          <%= link_to 'Supprimer le créneau', compost_timeslot_path(@compost, slot),  method: :delete, data: { confirm: 'Etes vous sure de vouloir supprimer le créneau ?' }, class: "btn btn-sm btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>